### PR TITLE
fix: remove dependency on derivative

### LINKED ISSUE #293: `derivative` is unmaintained; consider using an alternative
## Bug Report

cargo audit reported the following issue:

```shell
Crate:     derivative
Version:   2.2.0
Warning:   unmaintained
Title:     `derivative` is unmaintained; consider using an alternative
Date:      2024-06-26
ID:        RUSTSEC-2024-0388
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0388
Dependency tree:
derivative 2.2.0
└── pilota 0.11.8
    ├── volo-thrift 0.10.5
    │   ├── iceberg-catalog-hms 0.4.0
    │   └── hive_metastore 0.1.0
    │       └── iceberg-catalog-hms 0.4.0
    ├── iceberg-catalog-hms 0.4.0
    └── hive_metastore 0.1.0
```

### PR DESCRIPTION
**Pull request by flaneur2020**
## Motivation

fixes #293

## Solution

the `derivative` crate has been marked as unmaintained by a GitHub bot, and all repositories depending on `pilota` have received a warning issue regarding this.

this PR removes the dependency on `derivative` by using the `#[derive(Default)]` attribute [from the Rust stdlib](https://rust-lang.github.io/rfcs/3107-derive-default-enum.html) for unit enum variants. and manually generated `impl Default` for enums with non-unit variants (e.g., `Ok(String)`).

### CODE REVIEW

**Comment by PureWhiteWu** [comment]
Thanks very much for your contribution!
LGTM, PTAL @Millione

**Review by PureWhiteWu — DISMISSED** [review]

File: pilota-build/src/plugin/mod.rs [hunk 1]
```diff
@@ -391,18 +391,42 @@ impl Plugin for ImplDefaultPlugin {
...
+                            })
+                        }
+                    } else {
+                        // for non unit variant, we need to impl Default for the enum
+                        let enum_name = cx.rust_name(def_id);
+                        let variant_name = cx.rust_name(first_variant.did);
+                        let fields = first_variant
+                            .fields
+                            .iter()
+                            .map(|_| "Default::default()".to_string())
```
Comment (Millione) [inline pilota-build/src/plugin/mod.rs:413]: Maybe it's better for us to use absolute path to prevent confliction from user defined struct in IDL?

**Review by Millione — COMMENTED** [review]
Great work, a little tweaking maybe needed.

File: pilota-build/src/plugin/mod.rs (hunk 1 above)
Comment (flaneur2020) [reply pilota-build/src/plugin/mod.rs:413]: i have some concerns that the logic in this PR might have issues when dealing with named fields. however, i haven't found any cases involving named fields in the test cases. i'm not entirely sure if this approach is always correct or not.

could you please help provide an example of a possible conflict arising from user-defined structs in the IDL? I'll be happy to add it to the test cases to avoid such conflicts in this pull request.

Comment (Millione) [reply pilota-build/src/plugin/mod.rs:413]: You can add the following to the union.thrift to give it a try.

```thrift
struct Default { }
```

Comment (flaneur2020) [reply pilota-build/src/plugin/mod.rs:413]: oh indeed 😱, let me fix this. thank you for the information!

Comment (flaneur2020) [reply pilota-build/src/plugin/mod.rs]: fixed in 6934fef, PTAL 🫡

**Review by Millione — APPROVED** [review]
Thanks for your contribution!
